#!/usr/bin/env python3

from subprocess import check_call
from script.helpers import GitWrapper

def main():
    git = GitWrapper()
    check_call('rm -rf build_libs libav_build build-stamp configure-stamp'.split())
    check_call('git clean -x -d -f debian/'.split())
    def cmd():
        check_call('git clean -x -d -f'.split())
    git.foreach_submodule(cmd)

main()
