#!/usr/bin/env python

import os
from os import path
from subprocess import check_call

from script.helpers import run_foreach_submodule, GitWrapper

def main():
    git = GitWrapper()
    if path.exists('ffmpeg-mt-enabled'):
        os.remove('ffmpeg-mt-enabled')
    # Allow setups where both ffmpeg and ffmpeg-mt are checked out
    # simultaneously, and leave the directories alone in that case.
    if path.exists('ffmpeg-mt/.git') and not path.exists('ffmpeg/.git'):
        # ffmpeg should be an empty directory if things are right
        os.rmdir('ffmpeg')
        os.rename('ffmpeg-mt', 'ffmpeg')
        os.mkdir('ffmpeg-mt')
        if git.supports_nofetch:
            cmd = 'git submodule update --no-fetch'.split()
        else:
            cmd = 'git submodule update'.split()
        check_call(cmd + ['ffmpeg'])
        os.chdir('ffmpeg')
        check_call(cmd)

main()
