#!/usr/bin/env python

import os
import sys
from os import path
from subprocess import check_call

from script.helpers import GitWrapper

def main():
    print "Currently only ffmpeg-mt is supported."
    sys.exit(1)
    git = GitWrapper()
    open('ffmpeg-mt-disabled', 'w').close()
    if path.exists('ffmpeg-mt-enabled'):
        os.remove('ffmpeg-mt-enabled')
    # Allow setups where both ffmpeg and ffmpeg-mt are checked out
    # simultaneously, and leave the directories alone in that case.
    if path.exists('ffmpeg-mt/.git') and not path.exists('ffmpeg/.git'):
        # ffmpeg should be an empty directory if things are right
        os.rmdir('ffmpeg')
        os.rename('ffmpeg-mt', 'ffmpeg')
        os.mkdir('ffmpeg-mt')
        if git.supports_nofetch:
            cmd = 'git submodule update --no-fetch'.split()
        else:
            cmd = 'git submodule update'.split()
        check_call(cmd + ['ffmpeg'])
        os.chdir('ffmpeg')
        def func(cmd=cmd):
            check_call(cmd)
        git.foreach_module(func)

main()
