#!/bin/sh
set -e
mydir="$(pwd)"
if test -f "wrapper_export_version" ; then
  cd "$mydir"/libass
  ./configure --host=arm-none-linux-gnueabi --prefix="$mydir/build_libs" --enable-static --disable-shared
else
  cd "$mydir"/libass
  ./autogen.sh --host=arm-none-linux-gnueabi --prefix="$mydir/build_libs" --enable-static --disable-shared
fi
